import Head from 'next/head'

import Navbar from '../components/Navbar'

import Hero from '@/components/Hero'
import About from '@/pages/About'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kiaaaa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Hero />
        <About />
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  )
}
